# Generated by Django 5.2 on 2025-05-04 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_owner_lesson_owner"),
        ("users", "0004_subscribe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscribe",
            unique_together={("user", "course")},
        ),
        migrations.AddField(
            model_name="subscribe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата подписки"
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="is_active",
        ),
    ]
