# Generated by Django 5.2 on 2025-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_course_owner_remove_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео (RuTube, YouTube и т.д.)",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
